// Event semantics (ids, names, icons, colors, info-field meanings) extracted from
// the Eclipse TraceX viewer sources under third_party/tracex (TMLDefines.cs,
// EventTypeDict.cs, EventInfoDict.cs). Loaded by TraceX.html.
window.TX_EVENTS = {
  "1": {name: "Internal Thread Resume", icon: "IR", color: "#ff64c8", fields: ["Thread Ptr", "Previous State", "Stack Pointer", "Next Thread Ptr"]},
  "2": {name: "Internal Thread Suspend", icon: "IS", color: "#ff64c8", fields: ["Thread Ptr", "New State", "Stack Ptr", "Next Thread Ptr"]},
  "3": {name: "Enter ISR", icon: "IE", color: "#ff64c8", fields: ["Stack Ptr", "ISR Number", "System State", "Preempt Disable"]},
  "4": {name: "Exit ISR", icon: "IX", color: "#ff64c8", fields: ["Stack Ptr", "ISR Number", "System State", "Preempt Disable"]},
  "5": {name: "Internal Time-Slice", icon: "TS", color: "#ff64c8", fields: ["Next Thread Ptr", "System State", "Preempt Disable", "Stack"]},
  "6": {name: "Running", icon: "R", color: "#00dc05", fields: [null, null, null, null]},
  "10": {name: "tx_block_allocate", icon: "BA", color: "#64ffeb", fields: ["Pool Ptr", "Memory Ptr", "Wait Option", "Remaining Blocks"]},
  "11": {name: "tx_block_pool_create", icon: "PC", color: "#64ffeb", fields: ["Pool Ptr", "Pool Start", "Total Blocks", "Block Size"]},
  "12": {name: "tx_block_pool_delete", icon: "PD", color: "#64ffeb", fields: ["Pool Ptr", "Stack Ptr", null, null]},
  "13": {name: "tx_block_pool_info_get", icon: "IG", color: "#64ffeb", fields: ["Pool Ptr", null, null, null]},
  "14": {name: "tx_block_pool_performance_info_get", icon: "PI", color: "#64ffeb", fields: ["Pool Ptr", null, null, null]},
  "15": {name: "tx_block_pool_performance_system_info_get", icon: "PS", color: "#64ffeb", fields: [null, null, null, null]},
  "16": {name: "tx_block_pool_prioritize", icon: "PP", color: "#64ffeb", fields: ["Pool Ptr", "Suspended Count", "Stack Ptr", null]},
  "17": {name: "tx_block_release", icon: "BR", color: "#64ffeb", fields: ["Pool Ptr", "Memory Ptr", "Suspended", "Stack Ptr"]},
  "20": {name: "tx_byte_allocate", icon: "BA", color: "#3296c8", fields: ["Pool Ptr", "Memory Ptr", "Size Requested", "Wait Option"]},
  "21": {name: "tx_byte_pool_create", icon: "PC", color: "#3296c8", fields: ["Pool Ptr", "Start Ptr", "Pool Size", "Stack Ptr"]},
  "22": {name: "tx_byte_pool_delete", icon: "PD", color: "#3296c8", fields: ["Pool Ptr", "Start Ptr", null, null]},
  "23": {name: "tx_byte_pool_info_get", icon: "IG", color: "#3296c8", fields: ["Pool Ptr", null, null, null]},
  "24": {name: "tx_byte_pool_performance_info_get", icon: "PI", color: "#3296c8", fields: ["Pool Ptr", null, null, null]},
  "25": {name: "tx_byte_pool_performance_system_info_get", icon: "PS", color: "#3296c8", fields: [null, null, null, null]},
  "26": {name: "tx_byte_pool_prioritize", icon: "PP", color: "#3296c8", fields: ["Pool Ptr", "Suspended Count", "Stack Ptr", null]},
  "27": {name: "tx_byte_release", icon: "BR", color: "#3296c8", fields: ["Pool Ptr", "Memory Ptr", "Suspended", "Available Bytes"]},
  "30": {name: "tx_event_flags_create", icon: "EC", color: "#ff8000", fields: ["Group Ptr", "Stack Ptr", null, null]},
  "31": {name: "tx_event_flags_delete", icon: "ED", color: "#ff8000", fields: ["Group Ptr", "Stack Ptr", null, null]},
  "32": {name: "tx_event_flags_get", icon: "EG", color: "#ff8000", fields: ["Group Ptr", "Requested Flags", "Current Flags", "Get Option"]},
  "33": {name: "tx_event_flags_info_get", icon: "IG", color: "#ff8000", fields: ["Group Ptr", null, null, null]},
  "34": {name: "tx_event_flags_performance_info_get", icon: "PI", color: "#ff8000", fields: ["Group Ptr", null, null, null]},
  "35": {name: "tx_event_flags_performance_system_info_get", icon: "PS", color: "#ff8000", fields: [null, null, null, null]},
  "36": {name: "tx_event_flags_set", icon: "ES", color: "#ff8000", fields: ["Group Ptr", "Flags to Set", "Set Option", "Suspended Count"]},
  "37": {name: "tx_event_flags_set_notify", icon: "EN", color: "#ff8000", fields: ["Group Ptr", null, null, null]},
  "40": {name: "tx_interrupt_control", icon: "IC", color: "#91461e", fields: ["New Interrupt Posture", "Stack Ptr", null, null]},
  "50": {name: "tx_mutex_create", icon: "MC", color: "#730a50", fields: ["Mutex Ptr", "Inheritance", "Stack Ptr", null]},
  "51": {name: "tx_mutex_delete", icon: "MD", color: "#730a50", fields: ["Mutex Ptr", "Stack Ptr", null, null]},
  "52": {name: "tx_mutex_get", icon: "MG", color: "#730a50", fields: ["Mutex Ptr", "Wait Option", "Owning Thread", "Own Count"]},
  "53": {name: "tx_mutex_info_get", icon: "IG", color: "#730a50", fields: ["Mutex Ptr", null, null, null]},
  "54": {name: "tx_mutex_performance_info_get", icon: "PI", color: "#730a50", fields: ["Mutex Ptr", null, null, null]},
  "55": {name: "tx_mutex_performance_system_info_get", icon: "PS", color: "#730a50", fields: [null, null, null, null]},
  "56": {name: "tx_mutex_prioritize", icon: "XP", color: "#730a50", fields: ["Mutex Ptr", "Suspended Count", "Stack Ptr", null]},
  "57": {name: "tx_mutex_put", icon: "MP", color: "#730a50", fields: ["Mutex Ptr", "Owning Thread", "Own Count", "Stack Ptr"]},
  "60": {name: "tx_queue_create", icon: "QC", color: "#001996", fields: ["Queue Ptr", "Message Size", "Queue Start", "Queue Size"]},
  "61": {name: "tx_queue_delete", icon: "QD", color: "#001996", fields: ["Queue Ptr", "Stack Ptr", null, null]},
  "62": {name: "tx_queue_flush", icon: "QF", color: "#001996", fields: ["Queue Ptr", "Stack Ptr", null, null]},
  "63": {name: "tx_queue_front_send", icon: "FS", color: "#001996", fields: ["Queue Ptr", "Source Ptr", "Wait Option", "Enqueued"]},
  "64": {name: "tx_queue_info_get", icon: "IG", color: "#001996", fields: ["Queue Ptr", null, null, null]},
  "65": {name: "tx_queue_performance_info_get", icon: "PI", color: "#001996", fields: ["Queue Ptr", null, null, null]},
  "66": {name: "tx_queue_performance_system_info_get", icon: "PS", color: "#001996", fields: [null, null, null, null]},
  "67": {name: "tx_queue_prioritize", icon: "QP", color: "#001996", fields: ["Queue Ptr", "Suspended Count", "Stack Ptr", null]},
  "68": {name: "tx_queue_receive", icon: "QR", color: "#001996", fields: ["Queue Ptr", "Destination Ptr", "Wait Option", "Enqueued"]},
  "69": {name: "tx_queue_send", icon: "QS", color: "#001996", fields: ["Queue Ptr", "Source Ptr", "Wait Option", "Enqueued"]},
  "70": {name: "tx_queue_send_notify", icon: "SN", color: "#001996", fields: ["Queue Ptr", null, null, null]},
  "80": {name: "tx_semaphore_ceiling_put", icon: "CP", color: "#3dc5af", fields: ["Semaphore Ptr", "Current Count", "Suspended Count", "Ceiling"]},
  "81": {name: "tx_semaphore_create", icon: "SC", color: "#3dc5af", fields: ["Semaphore Ptr", "Initial Count", "Stack Ptr", null]},
  "82": {name: "tx_semaphore_delete", icon: "SD", color: "#3dc5af", fields: ["Semaphore Ptr", "Stack Ptr", null, null]},
  "83": {name: "tx_semaphore_get", icon: "SG", color: "#3dc5af", fields: ["Semaphore Ptr", "Wait Option", "Current Count", "Stack Ptr"]},
  "84": {name: "tx_semaphore_info_get", icon: "IG", color: "#3dc5af", fields: ["Semaphore Ptr", null, null, null]},
  "85": {name: "tx_semaphore_performance_info_get", icon: "PI", color: "#3dc5af", fields: ["Semaphore Ptr", null, null, null]},
  "86": {name: "tx_semaphore_performance_system_info_get", icon: "PS", color: "#3dc5af", fields: [null, null, null, null]},
  "87": {name: "tx_semaphore_prioritize", icon: "SR", color: "#3dc5af", fields: ["Semaphore Ptr", "Suspended Count", "Stack Ptr", null]},
  "88": {name: "tx_semaphore_put", icon: "SP", color: "#3dc5af", fields: ["Semaphore Ptr", "Current Count", "Suspended Count", "Stack Ptr"]},
  "89": {name: "tx_semaphore_put_notify", icon: "SN", color: "#3dc5af", fields: ["Semaphore Ptr", null, null, null]},
  "100": {name: "tx_thread_create", icon: "TC", color: "#ffff80", fields: ["Thread Ptr", "Priority", "Stack Ptr", "Stack Size"]},
  "101": {name: "tx_thread_delete", icon: "TD", color: "#ffff80", fields: ["Thread Ptr", "Stack Ptr", null, null]},
  "102": {name: "tx_entry_exit_notify", icon: "TE", color: "#ffff80", fields: ["Thread Ptr", "Thread State", "Stack Ptr", null]},
  "103": {name: "tx_thread_identify", icon: "TI", color: "#ffff80", fields: [null, null, null, null]},
  "104": {name: "tx_thread_info_get", icon: "IG", color: "#ffff80", fields: ["Thread Ptr", "Thread State", null, null]},
  "105": {name: "tx_thread_performance_info_get", icon: "PI", color: "#ffff80", fields: ["Thread Ptr", "Thread State", null, null]},
  "106": {name: "tx_thread_performance_system_info_get", icon: "PS", color: "#ffff80", fields: [null, null, null, null]},
  "107": {name: "tx_thread_preemption_change", icon: "CT", color: "#ffff80", fields: ["Thread Ptr", "New Threshold", "Old Threshold", "Thread State"]},
  "108": {name: "tx_thread_priority_change", icon: "CP", color: "#ffff80", fields: ["Thread Ptr", "New Priority", "Old Priority", "Thread State"]},
  "109": {name: "tx_thread_relinquish", icon: "RQ", color: "#ffff80", fields: ["Stack Ptr", "Next Thread Ptr", null, null]},
  "110": {name: "tx_thread_reset", icon: "RS", color: "#ffff80", fields: ["Thread Ptr", "Thread State", null, null]},
  "111": {name: "tx_thread_resume", icon: "TR", color: "#ffff80", fields: ["Thread Ptr", "Thread State", "Stack Ptr", null]},
  "112": {name: "tx_thread_sleep", icon: "TZ", color: "#ffff80", fields: ["Sleep Value", "Thread State", "Stack Ptr", null]},
  "113": {name: "tx_thread_stack_error_notify", icon: "SE", color: "#ffff80", fields: [null, null, null, null]},
  "114": {name: "tx_thread_suspend", icon: "TS", color: "#ffff80", fields: ["Thread Ptr", "Thread State", "Stack Ptr", null]},
  "115": {name: "tx_thread_terminate", icon: "TT", color: "#ffff80", fields: ["Thread Ptr", "Thread State", "Stack Ptr", null]},
  "116": {name: "tx_thread_time_slice_change", icon: "CS", color: "#ffff80", fields: ["Thread Ptr", "New Timeslice", "Old Timeslice", null]},
  "117": {name: "tx_thread_wait_abort", icon: "WA", color: "#ffff80", fields: ["Thread Ptr", "Thread State", "Stack Ptr", null]},
  "120": {name: "tx_time_get", icon: "TG", color: "#400080", fields: ["Current Time", "Stack Ptr", null, null]},
  "121": {name: "tx_time_set", icon: "TS", color: "#400080", fields: ["New Time", null, null, null]},
  "122": {name: "tx_timer_activate", icon: "TA", color: "#400080", fields: ["Timer Ptr", null, null, null]},
  "123": {name: "tx_timer_change", icon: "TC", color: "#400080", fields: ["Timer Ptr", "Initial Ticks", "Reschedule Ticks", null]},
  "124": {name: "tx_timer_create", icon: "CR", color: "#400080", fields: ["Timer Ptr", "Initial Ticks", "Reschedule Ticks", "Enable"]},
  "125": {name: "tx_timer_deactivate", icon: "TD", color: "#400080", fields: ["Timer Ptr", "Stack Ptr", null, null]},
  "126": {name: "tx_timer_delete", icon: "DE", color: "#400080", fields: ["Timer Ptr", null, null, null]},
  "127": {name: "tx_timer_info_get", icon: "IG", color: "#400080", fields: ["Timer Ptr", "Stack Ptr", null, null]},
  "128": {name: "tx_timer_performance_info_get", icon: "PI", color: "#400080", fields: ["Timer Ptr", null, null, null]},
  "129": {name: "tx_timer_performance_system_info_get", icon: "PS", color: "#400080", fields: [null, null, null, null]},
};
window.TX_OBJECT_TYPES = {
  "1": "Thread",
  "2": "Timer",
  "3": "Queue",
  "4": "Semaphore",
  "5": "Mutex",
  "6": "Event Flags",
  "7": "Block Pool",
  "8": "Byte Pool",
};
